name: Test, Build & Publish to TestPyPI

on:
  push:
    tags:
      - 'v*'
      - 'release*'
    branches:
      - update-python-dfr-django-versions

jobs:
  testing:
    name: Run Tests with Tox
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.5, 3.6, 3.7, 3.8, 3.9, 3.10.x, 3.11 ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Testing with Tox
        run: |
          pip install tox tox-gh-actions
          tox

  build-and-publish:
    name: Build and publish Python distribution to TestPyPI
    runs-on: ubuntu-latest
    needs: testing
    environment:
      name: testpypi
#      url: https://pypi.org/p/drf-fields-permissions/
    permissions:
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools & Build package
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          python -m pip install --upgrade build
          python -m build

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true # For Debugging in case of errors
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
